### ISSUE TITLE
Unable to add page break to an empty line

### ISSUE THREAD

**Issue by twoolworth** [DiemenDesign/summernote-pagebreak#1]
Our users often will add an empty line and then attempt to add the page break in that empty line which currently does not add the page break element. An example snippet would be with the summernote content of:
```html
<p>Hello</p>
<p><br></p> <!-- This is where they attempt to add the page break -->
<p>This is a test</p>
```

Looking into the code base I was able to determine that the line:
```js
var el = getSelection().getRangeAt(0).commonAncestorContainer.parentNode;
```
Would make `el` be set to the summernote editor itself which causes the breakage of not adding the page break element.

### Possible Solution
I was able to add one more check and reset `el` in this scenario which does then allow the user to add page breaks to blank lines. Here's the snippet I added to the click handler:
```js
if ($(el).hasClass('note-editable')) {
    el = getSelection().getRangeAt(0).commonAncestorContainer;
}
```

My complete click handler looks like:
```js
click: function (e) {
    e.preventDefault();
    if (getSelection().rangeCount > 0) {
        var el = getSelection().getRangeAt(0).commonAncestorContainer.parentNode;
        if ($(el).hasClass('note-editable')) {
            el = getSelection().getRangeAt(0).commonAncestorContainer;
        }
        if (!$(el).hasClass('page-break')) {
            if ($(el).next('div.page-break').length < 1)
                $('<div class="page-break"></div>').insertAfter(el);
        }
    } else {
        if ($('.note-editable div').last().attr('class') != 'page-break')
            $('.note-editable').append('<div class="page-break"></div>');
    }
}
```

### Other Notes
I think line 39 should actually be:
```js
if (!$(el).hasClass('page-break')) {
```
Where the period is removed in front of `page-break`

**Comment by DennisSuitters** [comment]
You're more than welcome to create a PR and add in your changes. I'm all open to working solutions, and if people add changes that benefit everyone. I'm a little occupied with something else at the moment (gathering firewood for winter), once I get a couple of hours free I'll have a look into it more.

**Comment by xnopasaranx** [comment]
I took the liberty of forking the repo and making a pull request as the plugin is essential for a project I am working on.
