### ISSUE TITLE
summernote duplicates pagebreaks on enter

### ISSUE THREAD

**Issue by xnopasaranx** [DiemenDesign/summernote-pagebreak#3]
# Issue Description:

when a pagebreak has been added and the cursor is on the same position as the pagebreak element, enter causes the pagebreak to be duplicated and so on.

This is apparently a problem with summernote itself, but since we have a workaround in place to circumvent this, I thought it would be a good idea to open an issue here.

# Workaround:
We have tried to understand how summernote handles key events and what exactly happens if enter is pressed. Since this is rather obfuscated, we have resorted to using a summernote callback in order to clean up:
```
onKeydown: function (e) { 
    if (e.keyCode === 13) {
        var $editor = $(e.target);
        setTimeout(function () {
            var $pageBreak = $editor.find(".page-break");
            $pageBreak.each(function (k, v) {
                var $nextElem = $(v).next();
                if ($nextElem.hasClass("page-break")) {
                    $nextElem.remove();
                }
            });
        }, 100)
    }
}
```
Note that we had to set a timeout, as in some cases it wouldn't work without.

**Comment by DennisSuitters** [comment]
Is this issue still occurring with the latest version of Summernote. I believe it's an issue that I think has since been resolved, not the actual plugin itself.

**Comment by DennisSuitters** [comment]
This is actually a known issue, pretty sure the other Summernote Devs are working on it, or may have fixed it by now. It's not the plugin causing it.
