### ISSUE TITLE
page-break div removed after submit

### ISSUE THREAD

**Issue by cristinaRobert** [DiemenDesign/summernote-pagebreak#4]
hello, I've problem using summernote-pagebreak.
After submiting a from summernote page-breake div removed!

**Comment by cristinaRobert** [comment]
Resolved automatically.
But in fact, I did not know what the problem was.

**Comment by cristinaRobert** [comment]
Any one here please?

**Comment by zeknoss** [comment]
I was having the same issue, you can simply fix it by adding this line after line 50:
`context.invoke('editor.insertText','');`

**Comment by DennisSuitters** [comment]
I believe the PR I just merged from @zeknoss fixes the issue @cristinaRobert
